badr_entr_commande_couleur:
    resource: "@BadrEntrCommandeBundle/Controller/CouleurController.php"
    type:     annotation
badr_entr_commande_couleur:
    resource: "@BadrEntrCommandeBundle/Controller/CouleurController.php"
    type:     annotation
badr_entr_commande_produit:
    resource: "@BadrEntrCommandeBundle/Controller/ProduitController.php"
    type:     annotation
badr_entr_boutique:
    resource: "@BadrEntrBoutiqueBundle/Resources/config/routing.yml"
    prefix:   /
badr_entr_commande:
    resource: "@BadrEntrCommandeBundle/Resources/config/routing.yml"
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"